version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: url_postgres
    environment:
      POSTGRES_DB: url_shortener
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: url_redis
    ports:
      - "6379:6379"

  backend:
    build: ./url-shortener-backend
    container_name: url_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/url_shortener
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

  frontend:
    build: ./url-shortener-frontend
    container_name: url_frontend
    ports:
      - "3053:80"
    depends_on:
      - backend

volumes:
  postgres_data: